blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/blendbyte/CoyoteCert/discussions
    about: Not sure if something is a bug? Start a discussion instead.
